### ISSUE TITLE
some character encoding error happens with the `ő` character

### ISSUE THREAD

**Issue by vilmosnagy** [curvednebula/api-docbaker-js#7]
to reproduce download this openAPI spec: https://opendata.bkk.hu/docs/futar-openapi.yaml (it's in hungarian & the API spec for the local public transport company)

then try to run `apibake`. The resulting PDF has some wierd characters in it:

[output.pdf](https://github.com/user-attachments/files/16236386/output.pdf)

![image](https://github.com/user-attachments/assets/3c24df53-d7d3-4c15-a285-48cc619a357e)

```
⛵ vnagy-eu in /tmp/apibake-character-encoding on ☁️  vilmos.nagy@realcity.io 
❯ wget https://opendata.bkk.hu/docs/futar-openapi.yaml 
futar-openapi.yaml.1 100% [===========================================================================================================================================================================================>]   35.05K    --.-KB/s
                          [Files: 1  Bytes: 35.05K [93.73KB/s] Redirects: 0  Todo: 0  Errors: 0                                                                                                                        ]

⛵ vnagy-eu in /tmp/apibake-character-encoding on ☁️  vilmos.nagy@realcity.io took 3s 
❯ apibake -h
ApiBake 0.1.25 - Convert OpenAPI spec to PDF.
Usage: apibake <openapi.json|.yaml|folder-name> [<file-or-folder2> <file-or-folder3> ...] [<options>]
Options:
 --out <string>: Output PDF file name.
 --title <string>: Document title.
 --subtitle <string>: Document sub title.
 --separate-schemas: When multiple API files parsed, create separate schemas section for each.
 --footer <string>: Defines content of common page footer. Options: "page-number". To turn off: "".
 --config <string>: Path to apibake-config.json. See --export-config.
 --export-config: Save default config into json file for editing.
 -h: Show this help.

⛵ vnagy-eu in /tmp/apibake-character-encoding on ☁️  vilmos.nagy@realcity.io took 3s 
❯ apibake futar-openapi.yaml
Parsing: futar-openapi.yaml
File info:
 - title: realCity Query Server API
 - description: Specification for the realCity Query Server API.
 - version: 1.0.1
Endpoints:
 - GET /{dialect}/api/where/alert-search
 - GET /{dialect}/api/where/arrivals-and-departures-for-location
 - GET /{dialect}/api/where/arrivals-and-departures-for-stop
 - GET /{dialect}/api/where/bicycle-rental
 - GET /{dialect}/api/where/booking-redirect
 - GET /{dialect}/api/where/metadata
 - GET /{dialect}/api/where/multi-route-details
 - POST /{dialect}/api/where/onboard-depart-search
 - GET /{dialect}/api/where/plan-trip
 - GET /{dialect}/api/where/plan-access
 - GET /{dialect}/api/where/references
 - GET /{dialect}/api/where/route-details-for-stop
 - GET /{dialect}/api/where/route-details
 - GET /{dialect}/api/where/schedule-for-stop
 - GET /{dialect}/api/where/search
 - GET /{dialect}/api/where/statistics
 - GET /{dialect}/api/where/stops-for-location
 - GET /{dialect}/api/where/ticketing-locations
 - GET /{dialect}/api/where/trip-details
 - GET /{dialect}/api/where/vehicle-for-trip
 - GET /{dialect}/api/where/vehicles-for-location
 - GET /{dialect}/api/where/vehicles-for-route
 - GET /{dialect}/api/where/vehicles-for-stop
Schemas:
 - ApiVersion
 - Dialect
 - ReferencesSchema
 - AlertSearchMethodResponse
 - EffectType
 - MobileTransitReferences
 - OTPTransitReferences
 - Status
 - TransitAgency
 - TransitAlert
 - TransitAlertRoute
 - TransitEntryWithReferencesTransitSearch
 - TransitReferences
 - TransitRoute
 - TransitRouteStyle
 - TransitRouteStyleIcon
 - TransitSearch
 - TransitStop
 - TransitStopStyle
 - TransitTrip
 - TransitVehicleStyleIcon
 - TranslatedString
 - ArrivalsAndDeparturesForLocationOTPMethodResponse
 - TransitDepartureGroup
 - TransitListEntryWithReferencesTransitDepartureGroup
 - TransitScheduleStopTime
 - ArrivalsAndDeparturesForStopOTPMethodResponse
 - TransitArrivalsAndDepartures
 - TransitEntryWithReferencesTransitArrivalsAndDepartures
 - BicycleRentalMethodResponse
 - TransitBikeRentalStation
 - TransitListEntryWithReferencesTransitBikeRentalStation
 - MetadataResponse
 - TransitEntryWithReferencesTransitMetadata
 - TransitMetadata
 - MultiRouteDetailsMethodResponse
 - TransitListEntryWithReferencesTransitRouteDetails
 - TransitPolyline
 - TransitRouteDetails
 - TransitRouteVariant
 - OnboardDepartSearchMethodResponse
 - TransitCoordinatePoint
 - TransitListEntryWithReferencesTransitVehicle
 - TransitVehicle
 - TransitVehicleOccupancy
 - TransitVehicleStyle
 - OnboardDepartPosition
 - TraverseMode
 - WalkProfile
 - ApiTripSearchMetadata
 - BikeStreetCategory
 - DisplayedLeg
 - ElevationPoint
 - EncodedPolylineBean
 - Itinerary
 - Leg
 - PatternStatistics
 - Place
 - PlanTripResponse
 - PlannerError
 - Response
 - TicketingLocation
 - TicketingPeriod
 - TransitEntryWithReferencesResponse
 - TripPlan
 - WalkStep
 - ReferencesMethodErrors
 - ReferencesMethodResponse
 - ReferencesMethodResult
 - RouteDetailsForStopMethodResponse
 - TransitListEntryWithReferencesTransitRoute
 - RouteDetailsMethodResponse
 - TransitEntryWithReferencesTransitRouteDetails
 - ScheduleForStopOTPMethodResponse
 - TransitEntryWithReferencesTransitSchedule
 - TransitRouteSchedule
 - TransitRouteScheduleForDirection
 - TransitSchedule
 - TransitScheduleGroup
 - SearchMethodResponse
 - StatisticsResponse
 - StopsForLocationResponse
 - TransitListEntryWithReferencesTransitStop
 - TicketingMethodResponse
 - TicketingProduct
 - TransitEntryWithReferencesTransitTicketing
 - TransitTicketing
 - TransitEntryWithReferencesTransitTripDetailsOTP
 - TransitTripDetailsOTP
 - TransitTripStopTime
 - TripDetailsOTPMethodResponse
 - VehicleForTripMethodResponse
 - VehiclesForLocationMethodResponse
 - VehiclesForRouteMethodResponse
 - VehiclesForStopMethodResponse
Saving output to output.pdf

```
